### ISSUE TITLE
Oxygen and Tool Shake

### ISSUE THREAD

**Issue by CJClaude** [SEServerExtender/SEServerExtender#10]
I may well be blind, I have a reputation for being so, but I'm not seeing the settings to enable/disable Tool Shake or Oxygen in either the Global Settings or World Settings.

Global:  http://puu.sh/gRVuF/dcdafaaa02.png

World:  http://puu.sh/gRVAh/90bd64018b.png

Ah, saw 1.75 is out... found Oxygen there, although tool shake is missing.

**Comment by dodexahedron** [comment]
I don't think tool shake has a property in the SE libraries, which is necessary for me to be able to put that in there (at least with the way it's currently done).
I'll have a look, tonight, as I probably just missed it when browsing through it.

**Comment by CJClaude** [comment]
Very VERY low priority for me, I only mentioned it because when I was 
searching for Oxygen, that came to mind.

**Comment by dodexahedron** [comment]
This is now in the code.
It will be in the next release, in a few minutes.
