### ISSUE TITLE
[v1.121.08.143-alpha] Frequent Server Crashes

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#103]
Thanks for this update, the debug command seems to have come in handy as I was getting crashes with nothing worthwhile in logs. This recent crash, extender provided the seemingly most informative output.

http://pastebin.com/p03bSpHZ

Hope this is helpful to you. If you need anything else, let me know.

Thanks

**Comment by rexxar-tc** [comment]
> at Sandbox.Game.Multiplayer.MySyncTextPanel.OnChangeFontSizeRequest(ChangeFontSizeMsg& msg, MyNetworkClient sender)

Can't say I've seen that one before. Smells like a genuine SE bug, so go post your log in the forum and let Keen take a look.

**Comment by EngineerBean** [comment]
Not that Keen acknowledged the post directly, but since the last hotfix, stability to the dedicated server seems to have returned. I am going to assume the issue has been resolved and i'll close it. Thanks for your input.
