### ISSUE TITLE
Link on space-z.de

### ISSUE THREAD

**Issue by w3z315** [SEServerExtender/SEServerExtender#108]
@dodexahedron  Hi there!
I'd like to post this as resource on http://space-z.de

Are you fine with that? :-)

**Comment by rexxar-tc** [comment]
As long as you link to this page or SEServerExtender.com, we're fine with it :)

**Comment by w3z315** [comment]
Awesome! :+1:  Do you have any Images e.g. a logo I can use?

**Comment by w3z315** [comment]
Nevermind: http://space-z.de/resource/seserverextender
