### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#109]
Since the last update I'm having the following issue: http://pastebin.com/SuJwLL5R.

**Comment by rexxar-tc** [comment]
You're using release 1.124, the current version is 1.126

**Comment by tdmike** [comment]
Yeah I'm seeing that I'm using a update script [(this one)](http://pastebin.com/0mFPBvEY) and it should update the game but it doesn't anymore.

**Comment by rexxar-tc** [comment]
You're using SESE release 1.124. You need to update it.

**Comment by tdmike** [comment]
O well, somewhere along the line I pretty much fucked up and copied the wrong files ...
