### ISSUE TITLE
SESE as a service crash on start

### ISSUE THREAD

**Issue by remygrandin** [SEServerExtender/SEServerExtender#113]
If you try to start SESE as a service, it crash instantly.

By debuging it locally, i've tracked down the problem here : 

https://github.com/SEServerExtender/SEServerExtender/blob/master/SEServerExtender/Program.cs#L376

The set of the console title throw an exception when in a service context as there is no console per se.

a simple fix would be : 

```
try
{
    if (string.IsNullOrEmpty (extenderArgs.ConsoleTitle) || string.IsNullOrWhiteSpace(extenderArgs.ConsoleTitle))
    {
        Console.Title = "SESE";
    }
    else
    {
    Console.Title = extenderArgs.ConsoleTitle;
    }
}
catch
{
}
```

**Comment by rexxar-tc** [comment]
Fixed in PR #114
