### ISSUE TITLE
1.140 Server startup Crash

### ISSUE THREAD

**Issue by imsupermario** [SEServerExtender/SEServerExtender#125]
I was updating the server from 1.138 to 1.140,
and I got the error message.

Here is the log:
http://pastebin.com/b18Qw4fY

Here are the system details:
OS:Windows Server 2012 R2
Processor: Common KVM processor 1.87GHz
Installed memory(RAM): 12 GB
Sytem type: 64-bit Operating System

**Comment by rexxar-tc** [comment]
Looks like you're somehow still on 1.138. I've had a few people report that SteamCMD isn't properly updating things. I just updated SESE to show your version number, so download it again and see what it says.
