### ISSUE TITLE
Timed actions are not priorized

### ISSUE THREAD

**Issue by darkcry** [SEServerExtender/SEServerExtender#126]
I have setup the extender to autosave every 10min, backup every hour (with the -1 value) and restarts every 4h.
It works as it should except for every 4th hour i miss a backup file. It looks like the restart operation does not wait until all other operations are completed. My workaround was to set the restarts 2min later. But for data integrity it should be fixed!
If actions are timed at the same time or intervall they has to be priorized.
1. All actions that change the gamestate (add/remove/edit things)
2. Then should be a autosave performed if intervall is met
3. Then should a backup happen if time is met
4. And last a restart should be performed if time is met

**Comment by rexxar-tc** [comment]
That's a lot of work for what is really a non-issue. Here's the official solution: don't run backups and restarts at the same time.
