### ISSUE TITLE
System Reflection Error / Server Crash - can't restart

### ISSUE THREAD

**Issue by tbankstemp** [SEServerExtender/SEServerExtender#130]
Server crash after a few minutes of running. I try to restart a few time, sometimes it works, other times I have to change random settings or clean the world and restart again seems to work (sometimes).

SESE: v1.150.01.660-alpha
Essentials: v1.13.07.243-alpha  (Also tried Essentials v1.13.07.237-alpha) To see if there was a difference but there wasn't. That's why I'm adding this to the SESE Issues list.

[SESE Console Log.txt](https://github.com/SEServerExtender/SEServerExtender/files/442862/SESE.Console.Log.txt)

[dot NET error.txt](https://github.com/SEServerExtender/SEServerExtender/files/442863/dot.NET.error.txt)

Thanks for looking at this and for all your hard work with this project!! I will also be donating again, cuz I wouldn't have a server without you :)

**Comment by rexxar-tc** [comment]
That error is a vanilla physics issue, I've been seeing it happen randomly on a lot of servers lately.

**Comment by tbankstemp** [comment]
Copy that, and thanks for looking. I'll submit a bug report.
