### ISSUE TITLE
[v1.153.03.737-alpha] Exception on use of '/delete all floating objects' command

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#134]
Subject line says it all..
[Captured Image](http://imgur.com/a/tgDu7)

**Comment by rexxar-tc** [comment]
Try "/delete all floatingobjects" ;)

**Comment by EngineerBean** [comment]
yeah, ok no worries. :)
I'd recommend you change the top line in the list of commands..
"/delete all floating objects — this should be obvious"
Save others from making the same silly mistake
and thanks...

**Comment by rexxar-tc** [comment]
oops, my bad :P
