### ISSUE TITLE
[Feature Request] Mass ownership change

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#137]
Last night I had a issue with my dedicated server, everyone who logged on got a new player id which caused them not be able to spawn on their ship or access them. It would be nice if we had a feature to mass change the ownerships. I have around 40 ships and/or stations in my server so it's quite a hassle to change every single ownership by hand. I can only imagine how it is on larger server.

**Comment by rexxar-tc** [comment]
Development on SESE has been halted permanently.
