### ISSUE TITLE
Welder not working.

### ISSUE THREAD

**Issue by Cookie1993** [SEServerExtender/SEServerExtender#14]
So, I have the weirdest thing going on right now, gonna try and explain it.
When I start the server with the "SpaceEngineersDedicated.exe" everything works just fine.
But with SESE, tried different versions, I can't equip a handheld welder.
Selecting the welder in the toolbar makes the highlighting blink, but goes back to "not highlighted".
Tried same/different worlds, same/different configs, with/without the EssentialsPlugin, with/without the mod installed, reinstalled Space Engineers and no errors or anything out of the ordinary in the logs.
I've got one in my inventory, tried making new ones,
Both the Drill and Grinder works just fine.

Anyone that could share some light on this?

**Comment by KodakYarr** [comment]
I have had this exact same problem and solved it. I will get back to you
later today when I get home from work. Hang tight!
/Kodak

**Comment by Cookie1993** [comment]
Awesome! Really want to try this out :)

**Comment by Cookie1993** [comment]
https://github.com/Tyrsis/SE-Community-Mod-API/issues/58
Found this, I'm also from Sweden xD
So changing format to UK(Server side) and setting everything manually in the date/time settings works perfect!
