### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by furtivesage** [SEServerExtender/SEServerExtender#16]
I added this version from your response the other alpha and page are no longer valid.  My DS launched, however within a couple of hours SEServerExt had consumed 12gigs of memory and the DS crashed.  I don't know enough to pinpoint, but for now I will go back to the vanilla launcher until this is resolved.  Thanks.

**Comment by dodexahedron** [comment]
Can you provide a copy of your world file?

**Comment by furtivesage** [comment]
Yes. What method?

**Comment by dodexahedron** [comment]
Dropbox or any other method you have available is fine by me.

-----Original Message-----

**Comment by furtivesage** [comment]
Ok, do you want a link to my dropbox?

**Comment by dodexahedron** [comment]
Just to the specific file is good enough.
I'm not picky. I just need the copy of the world so I can inspect and try to replicate the issue.

**Comment by furtivesage** [comment]
https://www.dropbox.com/sh/ikykiwll1ch3jue/AABLPP4MgxMT0puDLKQ1HjRTa?dl=0

**Comment by markam67** [comment]
This still seems to be an issue and it seems related to mining or at least to voxel modification the more you do the more the server seems to use up memory until you hit the physicial memory limits and the server box gets bogged down to the point that you have to perform a restart. I thought that this was more a keen mining related bug but now I am not too sure. I can also provide savegame if necessary. the truth is that you need to run the server and mine in the world to replicate bug. It is still not every time you mine either but does seem to be some kind of cumulative(over time) issue.

**Comment by dodexahedron** [comment]
A lot of memory leaks have been fixed in SE 1.85.
See how it behaves for you now.

**Comment by dodexahedron** [comment]
Just as a follow-up, SESE doesn't really acquire any unmanaged resources by itself, so I can't see how SESE could be responsible for this.
I'm closing this particular issue.
If a more specific culprit can be identified, feel free to open a new one.
