### ISSUE TITLE
System.AccessViolationException during Garbage Collection

### ISSUE THREAD

**Issue by zrisher** [SEServerExtender/SEServerExtender#17]
Hello,

I'm receiving the below error every 2-5 hours. It immediately kicks out all users and becomes unresponsive. Unfortunately, the UnresponsiveRestart from Essentials doesn't catch this state. This is the second world in a row I've had this problem with and it seems to pop up as soon as I begin using Extender:

```
Exception occured: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at hkMemoryRouter.heap(hkMemoryRouter* )
   at HkpAabbPhantomOverlapListener.__vecDelDtor(HkpAabbPhantomOverlapListener* , UInt32 A_0)
   at Havok.HkpAabbPhantom.Dispose(Boolean A_0)
```

It always appears right after a `GC Memory: XXX,XXX,XXX B` or a `Session snapshot save - END`.

The few places I could find people with the same error on Google, they pointed to it being an Extender issue but didn't have any supporting evidence. Have you seen this before? I have a lot of debugging to do but wanted to check in to make sure there wasn't a known issue I was unaware of.

**Comment by zrisher** [comment]
Looking at this forum post:
http://forums.keenswh.com/threads/01-077-005-ds-server-crash-after-saving.7357463/

It seems like I might need to do some SEToolBox work as detailed here:
http://www.hostedspaceengineers.com/forums/topic/server-cleaning-process/

I'll try that and report back.

**Comment by dodexahedron** [comment]
This is almost definitely a mod issue.  Extender doesn't do this on its own or I'd have a lot more unhappy people (including my own servers).  Extender also doesn't have anything to do with either of the log lines mentioned.  If extender throws an error, it'll look like all the other log lines extender writes out, with the timestamp, severity, and source.
Can you provide a copy of your world folder, as it currently exists (asteroids and all)?

**Comment by zrisher** [comment]
Thanks, just getting that info that no one else is having this problem is honestly really helpful. Felt like I was going crazy. 

I'm going to spend some time slowly and carefully debugging this on a test server this weekend until I get to the root cause. I'll report back. If I get to the point where all mods are gone, the world file is clean, but I'm still getting this issue I'll send you my files.

**Comment by togosh** [comment]
zrisher, I have had many AccessViolation errors in the past along with some other errors, just curious did you by chance change your world size from what you started it from?

**Comment by zrisher** [comment]
@stephen-cernota YES I believe I may have changed the world size from 500km to 300km. I noticed the death border actually occured 215km out from 0,0,0, which I thought was odd.

So am I going to need to remake my world?

**Comment by togosh** [comment]
http://forum.keenswh.com/threads/warning-modified-density-of-asteroids-is-not-supported.7313258/
(Specifically Post number 4)

:( I ran into the same issue two months ago, and they didnt have that pinned topic back than... LOL, glad I could help :)

(I run the Prometheus Rising servers: http://steamcommunity.com/groups/PrometheusRising I am in need of some technical, trustworthy admins if you or anyone reading this is interested)

**Comment by zrisher** [comment]
@stephen-cernota Hmmm, the error I've been encountering is always the one mentioned in the first post here, which doesn't seem to correlate with the problems they are suggesting. Regardless, I should probably gen a new world because it sounds like I've set myself up for problems. Thanks for the info!

This is my current server, [Gardens of Sajuuk](http://steamcommunity.com/groups/gardens_of_sajuuk). Looks like we have similar goals, I'm definitely interested in combining resources with like-minded people. We have about 12 active players right now but we've been growing quickly. I have to have the [Autopilot mod](https://github.com/Rynchodon/Autopilot), though, because I'm trying to publicize it and collect user feedback to improve it. If you're still interested hit me up on steam.

**Comment by zrisher** [comment]
I was able to reproduce this issue with Extender disabled yesterday - I believe Stephen is on the ball when he says this is due to some sort of world file corruption. Closing this ticket, thanks for your help.

**Comment by dodexahedron** [comment]
I'm curious to see the resolution here, though.  "World file corruption" is a dubious term, to me, since it's just a big XML file.
My suggestion, if you suspect a bad world, is to export all the cubegrids from the world in setoolbox and then add them back in in groups until you get the behavior again.  If there's a problem with a specific entity, that'll narrow it down to what.
This sort of this is almost always due to a mod, but it could be a bug in the base game, as well.

**Comment by zrisher** [comment]
The file itself is a big XML file, but when you combine it with game settings you get  a "world" that can render itself problematic. I.e. the issue that Stephen linked to - if you have a world file that was generated with a larger map size, then you change the server map size setting, you can get all sorts of problems.

TBH though I haven't managed to completely rule out mods yet, working on that now.

**Comment by dodexahedron** [comment]
There are very few cases where it even makes sense for world size to have an impact on world generation, and those cases are unlikely, anyway, as they would involve things like KSH using the world size as part of the RNG seed.
In any case, if turning mods off gets rid of the problem, there you have it (very likely).
If removing all mods does not take care of it, it's a SE issue and should be reported to KSH.

**Comment by dodexahedron** [comment]
BTW, that's something going on in the havok wrapper.
