### ISSUE TITLE
Repo should not be a fork

### ISSUE THREAD

**Issue by zrisher** [SEServerExtender/SEServerExtender#19]
If this is now the primary resting spot of this repo (which seems appropriate, something user-agnostic is easier for continued maintenace), it should be set up as its own base. Two reasons I can think of:
- The base repo is where any newcomer will search for the most current info and status of a project. Currently it would appear to them that the older versions are actually the primary reference points.
- Since this repo was forked from several others, we are unable to use Github's search function on its code.

**Comment by dodexahedron** [comment]
Agreed, and that's actually why I started the SEServerExtender2 project on here, so it can be a root.
There's a feature freeze on this version of Extender and Essentials, and any new features should be developed in the new project.

As for this one being a root...
There's a problem...
I could delete this repository and start it as a completely new one, but then we'd lose all change history.

Thoughts?

**Comment by zrisher** [comment]
Yeah if you deleted the repo, create a new, and upload your local copy - that would maintain the git commit history, but all github metadata like issues, releases, PRs, etc would be deleted. 

Apparently you can just contact Github support though and they can convert it to a standard repo without losing any of that:
http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by dodexahedron** [comment]
I contacted support today and both this repo and EssentialsPlugin have been extracted to be their own roots, now, with all children maintained in this network.

Closing this one.

**Comment by zrisher** [comment]
Yay thank you!
