### ISSUE TITLE
Exception when Saving (Autosave or /save)

### ISSUE THREAD

**Issue by awaldrop** [SEServerExtender/SEServerExtender#20]
![image](https://cloud.githubusercontent.com/assets/3308202/7303083/01484026-e9bc-11e4-8fb3-9f3f3543b2fe.png)

System.Reflection.TargetParamaterCountException: Parameter count mismatch.

The above error also occurs during the timed save period

Extender Version: 1.79.6.383

**Comment by dodexahedron** [comment]
The save method now takes an additional parameter.
Fix coming shortly.

**Comment by dodexahedron** [comment]
Fixed in 1.79.6.386

**Comment by awaldrop** [comment]
Thank you again for your continued support and work on this project!

**Comment by zrisher** [comment]
+1 thank you!

**Comment by dodexahedron** [comment]
I also noticed that it is possible to save from the KSH mod api, now, so I may end up moving the save methods  to calls into that to avoid future issues.

**Comment by dodexahedron** [comment]
I've moved several methods that were previously called through reflection to now be called through the KSH mod API.
The less that has to happen via reflection, the better.
Changes will be in the next release.
