### ISSUE TITLE
Exception when selecting a Solar Panel from Entities Tab

### ISSUE THREAD

**Issue by awaldrop** [SEServerExtender/SEServerExtender#22]
![image](https://cloud.githubusercontent.com/assets/3308202/7318931/c58d6b30-ea5e-11e4-9513-e9db9d9b3898.png)

Error: Method not Found at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)

Seems like there may be other blocks that could trigger this, but I've been able to reproduce it every time when I click on a solar panel. 

I was not actually trying to do anything with the solar panel (Miss click) but nothing seems obviously wrong other than the error popping in the console.

**Comment by dodexahedron** [comment]
Thanks for the report.
I'll fix that in the next update, which will probably be later tonight, if I am able to get to it.

-----Original Message-----

**Comment by dodexahedron** [comment]
Seems they removed the IMyFunctionalBlock interface from solar panels, which is why this no longer worked.
I swapped that out for the next best thing, which is IMyTerminalBlock.  The only drawback there is you can no longer enable/disable these in extender.
This will be in the next release.
