### ISSUE TITLE
Save World not function properly 

### ISSUE THREAD

**Issue by devu** [SEServerExtender/SEServerExtender#26]
2 versions ago (SEServerExtender-v1.79.08.411) I have noticed extender save functionality was working on initial start up twice. (Very slow btw hanging client screen for more than 10 sec. no longer async ?) Then, it was always giving this log:

Save already in progress. Save request canceled.

At least native autosave was working to keep the server going.

Now  it is impossible to run the server because above behavior exist and native one is disabled.
Even starting it without autostart flag.

**Comment by dodexahedron** [comment]
Clearly the KSH mod API save isn't safe.
Enough people seem to be having trouble with it that I'm going to roll that back.

-----Original Message-----

**Comment by dodexahedron** [comment]
How is this working ofr you, after an upgrade to *.418 and the newest version of essentials?

**Comment by dodexahedron** [comment]
Version 419 should be working properly with this.
Re-open the issue if it is still happening to you with version 419.
