### ISSUE TITLE
WCF - Integrate chat functionality

### ISSUE THREAD

**Issue by dodexahedron** [SEServerExtender/SEServerExtender#3]
The WCF service should allow chat functionality to be integrated.
Ideally, this will be two-way, but at least the ability to send messages as the server would be immensely useful.

**Comment by remygrandin** [comment]
And interesting way would be, for the "receiving" part of the service to be able to store and give, let's say the lastet 50-100 messages and to be able to give all the message published after either a timestamp or, if each message have an incrementing id, after one's id

**Comment by dodexahedron** [comment]
Hmm.
Ok, going to throw some ideas around, here.  See how these sound to you:

I will have to buffer it somewhere, then, in order for that to work.
If I keep it in memory, do we limit size of stored history or time history is kept before it will expire?  How large or long would those limits be?  I'd probably make the limits user-configurable, with some sanity limits.
If we write it to a file, same questions, but do we also clear that file on server exit or do we leave it around until the next time someone polls the service?
Maybe it is handled by a subscription mechanism, with a session.  As long as the session is active, messages are buffered to be sent on the next poll.  If the session dies, your buffer is lost.

Other ideas?
Thoughts on these ideas?

**Comment by dodexahedron** [comment]
I have a working implementation of this in SESE now.
Take a look at it and see how you like it.
It works like this:

There is now a ChatSessionManager, which manages chat monitoring sessions.
A WCF client can request to start a new monitoring session, which will add a session to the ChatSessionManager.
I have defined an event that fires when chat messages are sent or received through SESE.
When the event fires, the message is added to all chat  monitors in the ChatSessionManager.
When a WCF client calls GetChatMessages, all chat messages that have accumulated in its session are sent to that client and then cleared from the session.

From the client's point of view, the process is this:
1) Start session
2) Poll periodically for new messages and do whatever you want with them
3) End session when done

I'm closing this issue, as the feature is implemented, but if anyone has any suggestions on a different/better way to do it, by all means open up a new issue and reference this one.

**Comment by DigTron** [comment]
Loving this, nice one!
