### ISSUE TITLE
Autostart Instance feature not working with SESE .418

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/SEServerExtender#30]
Hey Dodex,

Downloaded the new essentials and extender and all the previous save issues have been resolved. When I tried to launch the server for the first time I got the following error:

2015-04-28 21:03:18.0369|Info|Auto-Start enabled
2015-04-28 21:03:18.0369|Info|Common instance pre-selected: 'OBG'
2015-04-28 21:03:18.0369|Info|Exception - {0}
    |System.NullReferenceException: Object reference not set to an instance of a
n object.
   at SEServerExtender.Program.Start(String[] args)

**Comment by dodexahedron** [comment]
Unfortunately, that doesn't tell me much.
Can you give me the actual log file output?  The logs in the console window are mostly for informational purposes and don't really help as much for debugging.  The logs in the files have additional information that helps a lot, in most situations.

**Comment by Ragnar24** [comment]
Sorry about that, now that I know I will reference logs for now on. If these are not the logs you are looking for please let me know.

http://pastebin.com/iC2EH45n

**Comment by dodexahedron** [comment]
Perfect.
As it turns out, I figured it out this morning.
But yes, those are the correct logs. Thank you.
It is now fixed in a62821ed7747c139b6dc326e98d64da3877183b5 (version 419).
Closing this and releasing.
