### ISSUE TITLE
SESE running as a service is looking in the System32 directory

### ISSUE THREAD

**Issue by mawh1** [SEServerExtender/SEServerExtender#31]
Hi

It appears the SESE wrapper cannot find SpaceEngineersDedicated.exe, because it is looking into the system32 directory. 

This is when its being run as a service, and SESE cannot start because of this. 

Thanks!

**Comment by dodexahedron** [comment]
You have to specify the working directory for the service.
Also, be sure to specify the gamepath argument.
See http://wiki.seserverextender.com/wiki/Command_Line_Options for a full list of command line options.
