### ISSUE TITLE
SESE .419 - Updates per Second not working

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/SEServerExtender#33]
Hey Dodex,

Not sure what the issue may be but after installing SESE 419 the Updates per Second does not give any readings. It stays at a constant 0 UPS. Here are the logs.

Plugins just in case:
https://www.dropbox.com/s/jlax05qnj397dyn/Orion-PluginLog-2015-04-29%20%281%29.log?dl=0

Server Extender Log:
https://www.dropbox.com/s/lry6d1w6a9n0hp1/Orion-SEServerExtenderLog-2015-04-29%20%281%29.log?dl=0

**Comment by dodexahedron** [comment]
Interesting.
The only time I ever get that behavior is when the setting to pause when nobody is online is turned on, and there is nobody online (so it is actually accurate, anyway).
Do you get UPS values other than zero when someone is actually in the server?

Other than that, I can't duplicate this.

**Comment by Ragnar24** [comment]
Yeah I have. I saw that it was 0 in the morning on boot up and figured I would wait till I got home from work to check it again. When I got home with 13 people online, it was still at zero and still is. I'll tamper with it and see if it's anything on my side.

**Comment by dodexahedron** [comment]
Odd.
Very odd.
However, with the update today, might be best to hold off on troubleshooting this, since no doubt things will change.

**Comment by Ragnar24** [comment]
After the new update this issue has been fixed. Now the UPS gives readings.

**Comment by dodexahedron** [comment]
Glad to hear it.

**Comment by Ragnar24** [comment]
Actually, it may be that it only occurs every now and then or that after I installed the newest essentials plugin, it no longer gives the UPS readings. Just to make sure I'm not being confusing, this is what I did.

Installed SESE .476
Ran the server without updating Essentials to .2407
UPS guage worked perfectly

Restarted server with Essentials .2407 update
UPS not working properly.

Not sure if it's a hit or miss thing or if essentials is directly related.

**Comment by dodexahedron** [comment]
Essentials isn't involved in the timer that refreshes that. It's pure coincidence.

-----Original Message-----

**Comment by MescalineMonkey** [comment]
I'm still having this problem. Any suggestions?

**Comment by dodexahedron** [comment]
Now that the source is available, perhaps this can be looked into.
It's super low-priority for me, though, since it doesn't really affect anything important.
