### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#36]
Quite possibly an error my end in something, still I need your assistance. Your 3 recent builds have not been working for me and i am getting this result.

http://pastebin.com/wpUFuvpr

using command line..  autostart instance="SpaceEng-1" autosave=10 wcfport=27016  logpath="C:\ProgramData\SpaceEngineersDedicated\SpaceEng-1\"

.386 was the last version that worked for me

**Comment by dodexahedron** [comment]
SESE version 1.80 requires space engineers version 1.80

-----Original Message-----

**Comment by EngineerBean** [comment]
I Have just discovered that the dedicatedserver.zip file included with SE Client was not updated by Keen. I have updated my server files via Steam SE dedicated server tool instead.
Thankyou for your response

**Comment by dodexahedron** [comment]
Excellent.
Happy engineering!
