### ISSUE TITLE
Concealment Debug Info displaying without toggling debug mode

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/SEServerExtender#38]
Hey Dodex,

The concealment debug string is being sent to the prompt even without toggling debug mode. I compiled a different version to get rid of this, just figured you would like to know if it was not done on purpose.

**Comment by dodexahedron** [comment]
It's not really intended to be a debug string. It's more of an audit log. However, I do intend to add an option in the configuration to show that message or not. I'll go ahead and add that for the next release.

-----Original Message-----

**Comment by dodexahedron** [comment]
The option is already there, apparently.
It just wasn't being respected.
I've put in the change and next release will both respect the setting and be quieter about it, anyway.

**Comment by dodexahedron** [comment]
Also, this is an essentials issue.
Closing, as it has been fixed and will be in Essentials 1.12.2.
