### ISSUE TITLE
the autostart option isnt autostarting

### ISSUE THREAD

**Issue by rcewl** [SEServerExtender/SEServerExtender#39]
the autostart option to get the server to start and restart it self doesnt work. (i need to manually hit the start button) i run these options "nowcf" , "autostart", "path="........""

the restart option is working again though ;) thx for that fix

**Comment by dodexahedron** [comment]
All of my servers use autostart, and it's working just fine.
There have been no changes to auto-start.
You have to specify an instance for autostart to work.
Here is the minimum command line for autostart to work:

SEServerExtender.exe instance="TestInstance" instancePath="C:\ProgramData\SpaceEngineersDedicated\TestInstance" autostart

And, of course,  you can add whatever other arguments you need for your specific instance.

**Comment by rcewl** [comment]
then the way commands are handle is changed ... worked fine on the old Tyrsis versions, when i changed to this new github release the nowcf only worked when it was called first (else server errored on the commands) and appearently autostart needs to be called last now?  can you fix this that is doesnt need to be in a set order ?

**Comment by rcewl** [comment]
https://github.com/rcewl/SE-PowerShell/blob/master/ExtenderRestart.ps1
i am using my (re)start script to update SE, update SEExtender and Essentials (automaticly sort out versions and when you uploaded new one to Github it will fetch it and install it) and it will call my cleanup script

it allso is used to start the server innitially (where it will run through severall checks on what platform it is running and if it should start extender or not) never had any problems with this .. but i had to move the nowcf to the front .. and i now will try moving autostart to the back.. allthough imo it shouldnt matter ;)

thx for the service Dodex

**Comment by rcewl** [comment]
ok.. moving autostart to the back of the line is working. allthough no the nowcf isnt read and it will use wcf... :(
so it looks like there is an issue with the way commands are handle

**Comment by dodexahedron** [comment]
This isn't a SESE issue.
Order of parameters does not matter.  The parser doesn't work that way.  It goes through every parameter passed to it by windows and sets the appropriate internal settings before continuing.
For example, I launched my test server all of the following ways, with identical results (auto-start of the correct instance):

SEServerExtender.exe autostart nowcf instance="TestInstance" instancePath="C:\ProgramData\SpaceEngineersDedicated\TestInstance"

SEServerExtender.exe autostart instance="TestInstance" instancePath="C:\ProgramData\SpaceEngineersDedicated\TestInstance" nowcf

SEServerExtender.exe nowcf instance="TestInstance" instancePath="C:\ProgramData\SpaceEngineersDedicated\TestInstance" autostart

SEServerExtender.exe nowcf autostart instance="TestInstance" instancePath="C:\ProgramData\SpaceEngineersDedicated\TestInstance"

Check your powershell script and print out the command line it executes, to see exactly what you're trying to do.
