### ISSUE TITLE
Error while autcleanup floating objects in enabled on server start

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#42]
When The Auto Clean After amount checkbox is clicked right at the start of the server the server gives the following error: http://pastebin.com/Z8CzNrar
This opens in a separate error window but somehow the server keeps running fine.

**Comment by dodexahedron** [comment]
I really feel like the auto cleanup is redundant with the game's built-in floating object limit.
The button to clean up all floating objects manually is nice, but the auto-cleanup seems pointless to me.
Thoughts?

**Comment by markam67** [comment]
I actually have wondered why this is in server extender as well. Is it a case of the floating cleanup was not originally available in SE without Server Extender? If so then maybe it is time to remove this feature other than a button for an instant cleanup.

**Comment by joemorin73** [comment]
I've never thought the SESE cleanup was too good either.  Even when I "cleanup", it removes it from the server, but I found it didn't remove it from the client machines.

**Comment by tdmike** [comment]
From my experience the button is a nice future to have but the check box with auto cleanup can be missed, since the built-in auto-cleanup seems to be working fine.

**Comment by SilentSymphony** [comment]
I've been hosting space engineers for a while now, I take care of keeping my servers clean and this feature has never been used in all of this time.

I don't see a need for it anymore, but having the option to have the timed cleanups clean the floating objects would be nice to keep around though, if the button/option is removed.

**Comment by dodexahedron** [comment]
Thanks for the feedback, everyone.
I'll be removing this from a future version of SESE.

**Comment by dodexahedron** [comment]
This was removed in 639721b448f4fb64657e22b79f7782ade27084a3
