### ISSUE TITLE
[v1.80.11.476-alpha] Character Entity and UPS updates

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#43]
In recent updates I have noticed characters are not showing in entity list and also UPS at bottom of extender is always at 0, doesn't seem to be updating. Both not major issues, but would be good if they worked again.

**Comment by dodexahedron** [comment]
Closing this issue as a duplicate of both #37 and https://github.com/SEServerExtender/EssentialsPlugin/issues/32
