### ISSUE TITLE
Plugins not being loaded 

### ISSUE THREAD

**Issue by ashein** [SEServerExtender/SEServerExtender#45]
I was recompiling the current version (5bb2a47) of SESE to use with Essentials, but the latter failed to be detected on server start. I suppose this happened because of _SEModAPIExtensions/API/PluginManager.cs:90_, the file scanning routines were changed on commit aeafa9fe. Swapping _GetDirectories_ with _GetFiles_ worked for me.

I'm not versed in github interfaces or in c# in general, so just leaving this in the unlikely case it would be useful.

**Comment by dodexahedron** [comment]
Plugins are intended to be dropped into their own folders inside the mods folder.
So, for example, Essentials would be placed in Mods/Essentials/ instead of just Mods/

**Comment by ashein** [comment]
Well, the plugin was in its respective subfolder, as per the instructions. Moreover, the downloadable release version of SESE saw and loaded it okay, but not the one compiled from the latest sources.

**Comment by dodexahedron** [comment]
Looks like this was a bug introduced in aeafa9fe6e09e3bcb0b7aba8d3c3ae7a01692d60
This has been fixed for version 1.83.8.489, which will be released shortly.

**Comment by remygrandin** [comment]
My bad everyone,  sorry,  I should have tested it better :-(

**Comment by dodexahedron** [comment]
No big deal. It was never released that way, I don't think.

-----Original Message-----
