### ISSUE TITLE
[v1.80.11.476-alpha] Server not starting under SE 1.083

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#47]
http://pastebin.com/KFXydzaw

Previous version of SE works fine under .476

P.S. Thankyou for your attention to the work of ShadowBlade and Conquest mode. It was at my request that he attempt it for my dedicated server. We have been throwing around ideas and much testing. It will be great to have you on board to help him where you can. :)

**Comment by dodexahedron** [comment]
I'm working on a fix right now.
It should be ready soon.

**Comment by dodexahedron** [comment]
This is fixed in 1.83.8.489.
