### ISSUE TITLE
Not able to start Extender as a service. 

### ISSUE THREAD

**Issue by mawh1** [SEServerExtender/SEServerExtender#52]
Hello! 

So for a while now ive not been able to start up extender as a service, it just goes to start, then fails and throws something in the extender log, and something else in the windows event log as an "application error". 

Note that before this started, it was working fine on 100+ sese enabled servers, so it seems to be something that happened in a recent update. 

Check here for the extender log: http://pastebin.com/rNRLhrfp 
Check here for the windows event application error log: http://pastebin.com/KnGESiPc

Let me know if you need anything else.
Thank you in advance.

**Comment by dodexahedron** [comment]
What is "a while?"
Can you give me a specific date or version of SESE/SE when things stopped working for you?  That might help me narrow down what might be happening for you.

There are no errors in the extender log you posted.

Where is SESE installed and what is the command line configured for the service?

**Comment by mawh1** [comment]
It stopped working with: v1.80.11.476-alpha But that was another error which should have been fixed in 489, but then it stopped working throwing the windows event error with version: v1.83.8.489-alpha 

Yeah i didnt think there was either, but it doesnt really say that its finished starting up either, and the windows event log links to extender. 

SESE is installed in the Space Engineers directory at C:\SpaceEngineers

It's run through SESM, unsure myself what the command line is for the service, i can ask Remy if necessary. However i think you may also be in contact.

**Comment by remygrandin** [comment]
Here are the starting arguments : 

noconsole
autosave={number}
instance={instancename}
instancepath={pathtoinstance}
logpath={pathtoinstance}
gamepath={pathtogamefilesfolder}

**Comment by dodexahedron** [comment]
The windows event log is always just going to show the application that was running (in this case, extender), rather than what necessarily caused the crash.  The stack trace in it can give details to that end, though.  There should have been two errors in your windows application event log, when the game crashed.  You gave me one of them (probably the second one, chronologically, judging by what it is).  Can you give me the other one?  It will be the one with a stack trace inside, which is a lot more useful.

**Comment by mawh1** [comment]
Ahh ok i see, sure i had a look, at it seems this is generated at the same time as the other log: http://pastebin.com/5vyitUg6

Hoping that is what you mean. 
When looking, i also saw this as the information level log, relating to server extender. Not sure if this is any help or related, but here it is anyway: http://pastebin.com/GNaGCA0N 
The second larger piece of text is the composition of the log file it links too.

**Comment by mawh1** [comment]
Been almost a week, haven't heard back yet, have you made any progress?

**Comment by dodexahedron** [comment]
The exception is happening in Havok.
This is almost definitely being caused by a mod.  It's definitely not a SESE issue.

**Comment by mawh1** [comment]
Hmm, I'm not so sure. I did run 100+ SESE servers for my company, 
Running on a brand new clean space engineers server, no mods, no nothing, a few weeks ago they were all working without issue, and now none of them will start with SESE enabled, since the version mentioned above. There have been no other changes.

**Comment by mawh1** [comment]
Further testing reveals I am able to start one SESE server. But only the one. Does that give you further insight into the issue?

**Comment by mawh1** [comment]
I just tried to run sese not through sesm, and get this error; http://prntscr.com/7dy689 a WCF problem. The already in use makes sense as of the inability to start a second sese server.

**Comment by dodexahedron** [comment]
Try adding the nowcf argument and see if you are able to get more than one.

**Comment by dodexahedron** [comment]
This sounds like it might be related to another issue, then.
I'm thinking the instance argument isn't being properly respected, because the instance argument is supposed to cause logs to be written to unique files as well as wcf to listen on a different address, and apparently neither of those things are working properly for people, right now.

**Comment by dodexahedron** [comment]
Hmmm.
You said it broke with 1.80 or it broke the version AFTER 1.80?
Argument parsing changed in 1.83, which was the next released version.

**Comment by mawh1** [comment]
There was one issue at 1.80, but that was solved in 1.83, however this error then started with 1.83
So yes, it started in 1.83 so it looks like it could be that

**Comment by mawh1** [comment]
I see it's marked as a bug now, but would you still like me to try starting it with the nowcf argument?

**Comment by dodexahedron** [comment]
That should at least keep it from blocking your start, yes.  But it's only a workaround - it's not an actual fix.

**Comment by dodexahedron** [comment]
I think one of these two commits is the source of the problem:
83281ae15a9053a112ad22ff446c633e64a1d15d
6e739ff79f8a7ea1556225843fb5f6f8e5704db3
I'll analyze the specific behavior in a bit.

**Comment by dodexahedron** [comment]
I found the culprit.
I have a version I'd like for you to test before I release it, if you don't mind.
Are you in the Skype SE modders group?

**Comment by mawh1** [comment]
That's great! I'm not in the modders group no, however i see you have released a patch for it now mentioning you fix this error. Thank you!
