### ISSUE TITLE
[Needs documenting]Recently concealed grids do not export sucessfully

### ISSUE THREAD

**Issue by DigTron** [SEServerExtender/SEServerExtender#54]
Observed this and thought it was worth noting before someone thinks its more serious than it is. Recently concealed and then exported grids are missing their CubeBlock and OxygenAmount info UNTIL a save occurs. 

So doing a '/save' before exporting resolves this.

**Comment by dodexahedron** [comment]
I'm not sure I follow the exact sequence, here.
Can you explain the steps to reproduce?
