### ISSUE TITLE
v1.83.8.489-alpha to current release... - No log files

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/SEServerExtender#57]
I have picked up on an issue with logfiles being written from SESE. Since v1.83.8.489-alpha update, I have not been seeing any log files in their regular place, nor can I find them if I do a file search. I have not changed my command-line arguments.

Command line used for execution is:
autostart instance="SpaceEng-1" autosave=10 wcfport=27016  logpath="C:\ProgramData\SpaceEngineersDedicated\SpaceEng-1\"

**Comment by dodexahedron** [comment]
Are the files ending up the the game executable directory, under a folder called logs?

**Comment by EngineerBean** [comment]
yes..as eg 'NoInstance-SEServerExtenderLog-2015-06-06.log'
Hence the reason I couldn't find them with filesearch.. as I was searching for SEServerExtender*.log
Thanks for that, at least I know where to look now for them..

Edit.. all that is in that file is '15:05:06.4344|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 5 arguments ...'

**Comment by dodexahedron** [comment]
If you launch extender with the instance argument, it shouldn't be doing that.
Let me have a look and see what's up.

**Comment by dodexahedron** [comment]
Ok, it looks like this is the same problem as #52 
I'm going to continue the troubleshooting in that thread.
