### ISSUE TITLE
Queries, issues and How To's

### ISSUE THREAD

**Issue by Ragonz2** [SEServerExtender/SEServerExtender#66]
Apologies if these have been answered before, I did take a look but didn't find anything.

So we are having a crack at getting SEServerExtender working within the confines of our game panel and whilst we can get it running that's all it does so is useless for people to use.

How do you add plugins to SESE when its being run from a commandline with no access to the GUI?

**Comment by dodexahedron** [comment]
Plugins are automatically loaded from the mods folder in your world save location, and the in-game commands offered by SESE and its plugins will work without access to a GUI.

-----Original Message-----
