### ISSUE TITLE
Enable/Disable Respawn ships missing from Control tab of SESE

### ISSUE THREAD

**Issue by FoxWyvern** [SEServerExtender/SEServerExtender#70]
The new world setting to have re spawn ships completely disabled/enabled is missing from the control tab of SESE. Does anyone know if I load the world up briefly in the default launcher and change the setting, and save, and go back to SESE, if that setting will remain in the world?

**Comment by dodexahedron** [comment]
It should work fine if you do that.
I'll put the setting in SESE the next time I am home and able to get to visual studio. I'm far away from that, right now.
It'll be a pretty easy addition.

**Comment by FoxWyvern** [comment]
Nice work :)
