### ISSUE TITLE
Errors/Warnings after recent SE update.

### ISSUE THREAD

**Issue by MescalineMonkey** [SEServerExtender/SEServerExtender#71]
Extender does not start after recent SE update.

**Comment by SilentSymphony** [comment]
my map was messed up when i first launched, i restored the world backup i made before i took it down to update and it ran fine, entity list freaks out, but other than that no crashes so far.

**Comment by MescalineMonkey** [comment]
![senostart](https://cloud.githubusercontent.com/assets/12192776/8365587/ae975aaa-1b53-11e5-9983-b4daa3f65ba3.jpg)

**Comment by MescalineMonkey** [comment]
SilentSymphony's suggestion of reverting to an earlier save worked. Server is up.
Still getting the yellow error and pink warning at the top though.

**Comment by dodexahedron** [comment]
Will address this tonight when I get home.

-----Original Message-----

**Comment by dodexahedron** [comment]
Fixed in 1.88.11.540, which will be released momentarily.

**Comment by DjKiDD** [comment]
Thank you!
