### ISSUE TITLE
extender 1.88.11.543 Space engineers 1.089 - CharEntity reflection validation failed

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/SEServerExtender#73]
extender 1.88.11.543 Space engineers 1.089 - CharEntity reflection validation failed
015-07-02 22:48:29.9558|Warn|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|CharacterEntity reflection validation failed!

from the extender logfile

**Comment by tdmike** [comment]
Same Problem here, same versions. But Server does not seem to have any troubles with it since it start just fine.

**Comment by dodexahedron** [comment]
Several of the fields that were causing this problem weren't actually being used by SESE, so I have removed them in version 558.
The way the game handles character health changed, though, and that was also causing the problem.  That has also been fixed in version 558.
558 will be released shortly.
