### ISSUE TITLE
SESE 1.88.11.543 Sun Rotation Interval

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#74]
After making a new world (and cfg) I was greeted with the following problem

Field not found: 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_SessionSettings.SunRotationIntervalMinutes'.

full cfg here: http://pastebin.com/gUswiDc2

The line containing the Rotation Interval is in the cfg

**Comment by haximodor92** [comment]
I have the same problem.

**Comment by dodexahedron** [comment]
Will have a look at this.
May be fixed in 558, but I haven't confirmed yet.

**Comment by tdmike** [comment]
Seems to be working fine after last update :)
