### ISSUE TITLE
 http://wiki.seserverextender.com - is private

### ISSUE THREAD

**Issue by wweiland** [SEServerExtender/SEServerExtender#78]
Unable to read material at  http://wiki.seserverextender.com as it is private.

**Comment by dodexahedron** [comment]
Huh.
That's odd.
The configuration on the server hasn't been changed.
What IP address do you get when you ping wiki.seserverextender.com?

**Comment by dodexahedron** [comment]
Problem has been resolved.
Apparently apache hadn't been reloaded since another site was modified, and that site's configuration clobbered almost every other site on the sytem, after a restart of apache.
