### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#79]
Just tried to run two instances of se dedicated server with SESE but ran in to a problem, the WCF Listener seems to be using a hardcoded port. Thus making it impossible to run two instances from the same installation, is it a possibility to setup differend ports for differend instances?

**Comment by markam67** [comment]
tdmike,

All you need to do is open the SEServerExtender.exe.config file and change the following line

```
<add key="WCFServerServiceBaseAddress" value="http://localhost:5353/ServerService/"/>
```

You can change the base address to any port you have open I usually use 5354 for the alternate server I run on my server machine. You will have to set the address for each instance you want to run concurrently. 

Markam67

**Comment by tdmike** [comment]
In that case I would have to copy my installation and change it in that one, that I understand I asked if it's possible to run two instances from the SAME installation...

**Comment by dodexahedron** [comment]
Launch with an instance name. That will cause it to listen on a unique address.
Otherwise, you can disable wcf entirely with the nowcf switch.

-----Original Message-----

**Comment by markam67** [comment]
Well live and learn I did indeed run two different directory copies of the server software and SESE. However I didn't know I could just turn off the WCF.

**Comment by markam67** [comment]
Dode,
I will have to try it again but I thought I had tried launching an instance in the same directory and still had the listener already in use error. I did not try the nowcf switch, however does that mean you can not use the gui for each instance with wcf disabled?
Thanks,
Markam67

Date: Tue, 28 Jul 2015 08:50:35 -0700

**Comment by tdmike** [comment]
Even with a instance name it gives a listening error that the port is already in use

**Comment by markam67** [comment]
I thought so. It seems that the instance name only does not prevent the listener error. 

tdmike, Did you try the nowcf switch?

**Comment by tdmike** [comment]
Nope still greeted with the following error.
![untitled](https://cloud.githubusercontent.com/assets/6142706/8987145/dd54dd16-36df-11e5-828f-b7e008e31c6c.jpg)

**Comment by tdmike** [comment]
Well apparently I made an error somewhere along the way because I got it working, with wcf enabled.
