### ISSUE TITLE
Does SESE still conflict with the official drive?

### ISSUE THREAD

**Issue by haximodor92** [SEServerExtender/SEServerExtender#81]
I know that SESE conflicted with those FTL MOD on the workshop and will cause the ship disappeared after FTL jump.

Right now the official updated the jump drive. I tested it on my dedicated server for several times. And sometimes-yes I mean sometimes, no always-the ship still disappear after jump drive.

I want to know if it is the problems of SESE.

**Comment by markam67** [comment]
Haximodor92,

That was reported on the Keen forums and acknowledged as a Keen bug and was supposedly addressed recently.
