### ISSUE TITLE
Error while restarting Dedicated Server

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#83]
Since a day or two I get this error messages everytime it does a automated restart

<img width="570" alt="untitled" src="https://cloud.githubusercontent.com/assets/6142706/9089016/5c57e77c-3b93-11e5-9e07-2b70115c54b0.png">

**Comment by MescalineMonkey** [comment]
I've been getting the same for a while now.

**Comment by tdmike** [comment]
Seems like the restart script is actuallly restarting the dedicated server software before it is fully shutdown

**Comment by dodexahedron** [comment]
This is a tricky problem to solve in windows, sometimes.
I'll make the restart be a more formal system instead of the batch file that is currently used, to fix this issue.

**Comment by tdmike** [comment]
It might be worth looking in to making it a proper service. In that way you can simply use Microsoft's system. Which I have to say works pretty well. If needed I can give you a hand. I have some experience with writing services.
