### ISSUE TITLE
Cant Change Worldname

### ISSUE THREAD

**Issue by tdmike** [SEServerExtender/SEServerExtender#86]
When Chaning the world name in de settings dialog of WCF, it does not actually change. The Name contained in the Sandbox.sbc needs to be changed to change the world name shown in the Server List.

**Comment by dodexahedron** [comment]
None of the names contained in the Keen launcher change anything in Sandbox.sbc.  It sets the names in SpaceEngineers-Dedicated.cfg
What tag are you saying needs to be set in Sandbox.sbc?

**Comment by McyD** [comment]
This is a well known issue.  To actually change a world name is has to be changed in the sandbox.sbc.  Its the fifth line of the sbc:

< SessionName>A World Name< /SessionName >

Even changing it in the vanilla launcher does not work and it has to be manually edited to change the world name.  This is the name that shows up on the server list, not the name in the config.
