### ISSUE TITLE
get_PowerReceiver method not found

### ISSUE THREAD

**Issue by devu** [SEServerExtender/SEServerExtender#87]
This fills up my logs from some time but because there was no visible implication in game I didn't reported this earlier. 

But some weird behavior reported by players my actually be a consequence of this:

Error: Failed to find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust' 

same apply to Gyro reactor and pretty much any powered Block.

**Comment by dodexahedron** [comment]
I will definitely have to look into that one.
Can you give me the full log file (pastebin)?

-----Original Message-----

**Comment by devu** [comment]
Here is just a fraction of it:

2015-08-28
21:24:51.9428|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished
loading SandboxGameAssemblyWrapper
2015-08-28
21:24:52.0719|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All
main types passed reflection unit tests!
2015-08-28
21:24:52.1420|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All
entity types passed reflection unit tests!
2015-08-28
21:24:52.2501|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All
block types passed reflection unit tests!
2015-08-28 21:24:52.2501|Info|SEModAPIExtensions.API.Server..ctor|Finished
creating server!
2015-08-28
21:24:52.2761|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished
loading DedicatedServerAssemblyWrapper
2015-08-28
21:24:52.2761|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished
loading PluginManager
2015-08-28
21:24:52.3152|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished
loading FactionsManager
2015-08-28
21:24:52.3192|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished
loading EntityEventManager
2015-08-28
21:24:52.4303|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished
loading ChatManager
2015-08-28
21:24:52.4303|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Common
instance pre-selected: 'Space1'
2015-08-28
21:24:52.4303|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Full
path pre-selected: 'C:\Serwery\SE\Space1'
2015-08-28
21:24:52.4303|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end
parsing
2015-08-28 21:24:52.4303|Info|SEServerExtender.Program.Start|Opening up WCF
service listener at http://localhost:5353/ServerService/Space1
2015-08-28
21:25:33.6008|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading
Session Settings
2015-08-28
21:25:38.4815|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 32
2015-08-28
21:25:38.4815|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode:
PUBLIC
2015-08-28
21:25:38.4815|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode:
Survival
2015-08-28
21:25:38.4815|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario:
Asteroids
2015-08-28
21:25:38.4815|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World
Size: 0

2015-08-28
21:25:38.6186|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished
loading PlayerManager
2015-08-28
21:25:38.6186|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished
loading NetworkManager
2015-08-28
21:25:42.5934|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished
loading PlayerMap
2015-08-28
21:27:26.9776|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished
loading SandboxGameAssemblyWrapper
2015-08-28
21:27:27.0417|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All
main types passed reflection unit tests!
2015-08-28
21:27:27.0837|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All
entity types passed reflection unit tests!
2015-08-28
21:27:27.1608|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All
block types passed reflection unit tests!
2015-08-28 21:27:27.1638|Info|SEModAPIExtensions.API.Server..ctor|Finished
creating server!
2015-08-28
21:27:27.1638|Info|SEModAPIInternal.API.Server.DedicatedServerAssemblyWrapper.get_Instance|Finished
loading DedicatedServerAssemblyWrapper
2015-08-28
21:27:27.1638|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished
loading PluginManager
2015-08-28
21:27:27.1778|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished
loading FactionsManager
2015-08-28
21:27:27.1778|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished
loading EntityEventManager
2015-08-28
21:27:27.2019|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished
loading ChatManager
2015-08-28
21:27:27.2019|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Common
instance pre-selected: 'Space1'
2015-08-28
21:27:27.2019|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|Full
path pre-selected: 'C:\Serwery\SE\Space2'
2015-08-28
21:27:27.2019|Info|SEModAPIExtensions.API.Server.ProcessCommandLineArgs|end
parsing
2015-08-28 21:27:27.2019|Info|SEServerExtender.Program.Start|Opening up WCF
service listener at http://localhost:5354/ServerService/Space1
2015-08-28
21:27:51.3470|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading
plugins ...
2015-08-28
21:27:51.3640|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning:
C:\Serwery\SE\Space1\Mods
2015-08-28
21:27:51.3981|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished
loading plugins
2015-08-28
21:27:51.3981|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing
plugins ...
2015-08-28
21:27:51.3981|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing
plugin at C:\Serwery\SE\Space1\Mods\Essentials\Essentials.dll -
f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-08-28
21:27:52.2269|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing
plugin at C:\Serwery\SE\Space1\Mods\SEPL\SEPL_Enforcement.dll -
dadf6dcf-e27d-43d7-8186-b64abd4ef107'
2015-08-28
21:27:52.2269|Info|SEModAPIExtensions.API.PluginManager.Init|Finished
initializing plugins
2015-08-28
21:27:57.9754|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading
Session Settings
2015-08-28
21:28:02.8831|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 32
2015-08-28
21:28:02.8831|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode:
PUBLIC
2015-08-28
21:28:02.8831|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode:
Survival
2015-08-28
21:28:02.8831|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario:
Asteroids
2015-08-28
21:28:02.8831|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World
Size: 300

2015-08-28
21:28:02.9832|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished
loading PlayerManager
2015-08-28
21:28:02.9832|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished
loading NetworkManager
2015-08-28
21:28:06.9440|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished
loading PlayerMap
2015-08-28
21:29:31.0167|Info|SEModAPIInternal.API.Common.WorldManager.get_Instance|Finished
loading WorldManager
2015-08-28
21:30:24.8824|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading
plugins ...
2015-08-28
21:30:24.8824|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning:
C:\Serwery\SE\Space2\Mods
2015-08-28
21:30:24.9104|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished
loading plugins
2015-08-28
21:30:24.9154|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing
plugins ...
2015-08-28
21:30:24.9154|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing
plugin at C:\Serwery\SE\Space2\Mods\Essentials\Essentials.dll -
f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-08-28
21:30:25.8814|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing
plugin at C:\Serwery\SE\Space2\Mods\SEPL\SEPL_Enforcement.dll -
dadf6dcf-e27d-43d7-8186-b64abd4ef107'
2015-08-28
21:30:25.9164|Info|SEModAPIExtensions.API.PluginManager.Init|Finished
initializing plugins
2015-08-28
21:30:38.8348|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass46_0.<AsynchronousSaveWorld>b__2|Asynchronous
Save Setup Started: 327.3146ms
2015-08-28
21:30:47.8224|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass46_0.<AsynchronousSaveWorld>b__0|Asynchronous
Save Completed: 9314,943ms
2015-08-28
21:31:06.4994|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.5304|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type
'Sandbox.Game.Entities.Cube.MyLandingGear'
2015-08-28
21:31:06.5384|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.5384|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.5564|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.5975|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6015|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.6645|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:06.6645|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6645|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6645|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6645|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6775|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.6775|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.6936|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7096|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7346|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7666|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7666|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.7716|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:06.7716|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7716|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.7716|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.8207|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.8207|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.8207|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.8207|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.9118|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.9118|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.9118|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:06.9118|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.9478|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:06.9788|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0309|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0309|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0309|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0789|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0879|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.0879|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.0879|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:07.1440|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.2571|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.3091|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.3091|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.3202|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.3202|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:07.3352|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.3352|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.4633|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:07.6565|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.6565|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.6785|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.7886|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.8777|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.9057|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.9157|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.9157|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:07.9878|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:08.0839|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.1339|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:08.2080|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:08.2110|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.2350|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.2701|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.3361|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.3922|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.3962|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.4332|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyThrust'
2015-08-28
21:31:08.4653|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:08.5413|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyGyro'
2015-08-28
21:31:08.5613|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'
2015-08-28
21:31:08.5704|Error|SEModAPI.API.Utility.Reflection.HasMethod|Failed to
find method 'get_PowerReceiver' in type 'Sandbox.Game.Entities.MyReactor'

And this continues for few more hundred of lines.

Each time when I do remove or paste some grid it seems happening again on
that particular grid.

**Comment by tdmike** [comment]
It also happends when you're in the Entities Window -> Sector Object -> Cube Grids, every single grid there causes the console to be spammed with the get_PowerReciever error

**Comment by dodexahedron** [comment]
That makes sense, based on what that is.
I'll work on a fix when I'm home, later this weekend. In theory, it should be generally cosmetic only.

-----Original Message-----

**Comment by devu** [comment]
Not sure if this is related, but my players reporting disappearance of ships when merging 2 small grids. In fact when they merging grids same log shows lack of method on MyShipMegeBlock as well.
