### ISSUE TITLE
Server crashes on startup following most recent Space Engineers update.

### ISSUE THREAD

**Issue by MescalineMonkey** [SEServerExtender/SEServerExtender#89]
![deleteme](https://cloud.githubusercontent.com/assets/12192776/10089340/e0d804ac-62e7-11e5-97cc-e09f0ea72845.jpg)

**Comment by SilentSymphony** [comment]
yep, same here.

**Comment by devu** [comment]
And here... I'm no longer able to run the server in pure vanilla mode due to the world set up. So I guess it's a game over for this weekend.

**Comment by dodexahedron** [comment]
I'll have a look when I get home this evening.

-----Original Message-----

**Comment by SilentSymphony** [comment]
Thanks dodex!

**Comment by McyD** [comment]
2015-09-25 00:48:46.1867|Info|Finished loading SandboxGameAssemblyWrapper
2015-09-25 00:48:46.2287|Error|System.Exception: Could not find internal type for PowerManager
   at SEModAPIInternal.API.Common.PowerManager.ReflectionUnitTest()
2015-09-25 00:48:46.2287|Warn|PowerManager reflection validation failed!
2015-09-25 00:48:46.2937|Error|AppDomain.UnhandledException - System.TypeLoadException: Could not load type 'Sandbox.ModAPI.Ingame.IMyPowerProducer' from assembly 'Sandbox.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests()
   at SEModAPIExtensions.API.BasicUnitTestManager.Run()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)

**Comment by ZilgornZeypher** [comment]
Same

**Comment by Cleaner409** [comment]
Same sounds like they changed a few things in the ModAPI code.

**Comment by dodexahedron** [comment]
What's really dumb is they've been removing some interfaces that really don't make sense to remove.
They removed IMyPowerConsumer a while ago, and with this update they apparently removed IMyPowerProducer.
...Yet most of the objects that used to inherit from those interfaces still have the properties they got from that interface... Only they no longer have a sensible inheritance tree, for having anything to do with power consumption/production.
Annoying.
This will take a little longer to fix than just a quick class relocate.

**Comment by zrisher** [comment]
They made significant changes to the power system it seems. ResourceDistributionGroups.sbc now contains the "sinks" and "sources" priorities which probably are there to support their new "turn stuff off on overload" system.

**Comment by Cleaner409** [comment]
They have an agenda. There is something they don't know how to do so they put the limitation on the mod community to solve it for them. Its normal keen operations, its been done 100 times before by them. Prepare for keens soon to come plagiarism.

**Comment by SilentSymphony** [comment]
thanks for the update dodex, No complaints here!

**Comment by SourPatchNom** [comment]
Dodex do you have anywhere that I could donate for your work? Or a way to private message you? Thank you for looking into this btw.

**Comment by dodexahedron** [comment]
I have pushed new code to github, that solves the compile errors.
However, since I haven't tested it yet, I didn't put up a binary release.
I'll try to get to that tonight, if I can.  Busy weekend coming up.

**Comment by dodexahedron** [comment]
As for private messaging me, I'll put up a contact method in the near future. For now, you can try to get me on Skype in the "Official SE/ME modding group" (Brandon Thetford)

**Comment by markam67** [comment]
Thank you for all the work you are doing maintaining the Extender. I know that lately Keen has not made it easy for Modders and Thirdparty users of the ModAPI.

**Comment by Cleaner409** [comment]
Can we repack this and test it somehow for you? I'm not the best with SE code as I am learning but if I know how I will give it a try. A-lot of servers have been down since keens patch bomb including mine.

**Comment by dodexahedron** [comment]
I'll put out a binary release so you can play with it.
Be aware that I still have not tested it, though.  Crazy week...

**Comment by SilentSymphony** [comment]
loaded the release you just put out, errors near the top about reflection during load, the errors near the end are when i clicked the entity tab.
Here's the log http://puu.sh/koWXS/bdeacf455f.txt

edit: reloaded server and without clicking the entitys tab everything is looking good other than the above stuff, joining my server now to make sure it doesn't throw some more errors.

Edit:2 http://puu.sh/koXZf/539b2de29c.jpg "server" inst showing before the name when i speak from the gui, the server as a whole seems to be running fine aside from the errors in the log i posted im accepting players, conceal/reveal is working, motd is working.

Edit3: My users are reporting no issues as of yet, we've been online since 12:30PM CST

**Comment by MescalineMonkey** [comment]
![deletemetoo](https://cloud.githubusercontent.com/assets/12192776/10119387/68d084a6-645a-11e5-806b-005c60f1ec70.jpg)
I'm getting this on startup.

**Comment by Cleaner409** [comment]
Server is running for now I am getting the same errors already posted and small bits of lag spikes. I assume the lag spikes and graphic stop is because of keens recent "Performance increase patch" as it does it in vanilla servers as well.

Dodex thank you for all your hard work it is appreciated by more people than you know.

**Comment by wweiland** [comment]
Any updates?

**Comment by Ragonz2** [comment]
This issue is occurring for us as well. tried the latest stable version and the latest pre-release version, neither works (either from loading sese from commandline or just opening the exe straight from the desktop.

Any updates on the situation would be appreciated.

**Comment by dodexahedron** [comment]
I'll give it a good look after tomorrow's update.
I wasn't really able to give it the time of day this past week, but I'll be able to check it out tomorrow night.
