### ISSUE TITLE
Exe for chat only

### ISSUE THREAD

**Issue by ghost** [SEServerExtender/SEServerExtender#91]
As title say, can you make a exe only for give us ability to send chat message without join in game?

Many times happens that i update my game but on my server there are other users and i can't join for ask to quit and let me update the server, then i must wait... 50% users wait and other 50% play in the server with a old version.

Im good in .NET but not too much in C#, i will try to separate the chat and make a single exe, (i can with your code?) but i think that is better and more fast if are you to do this :)

**Comment by Devlah** [comment]
SESE lets you chat with players without joining the game.  It's in the "Chat" tab of SESE.....

**Comment by ghost** [comment]
Emh... i know...
I mean, now i cant use SESE bacause when i start is, there are many many error... one error every second... Then im waiting a new release.

**Comment by dodexahedron** [comment]
That shouldn't affect your use of the chat tab.

**Comment by ghost** [comment]
I know, but was just a suggestion :)

**Comment by ghost** [comment]
OK, now the app crash at startup, then i cant do nothing except dont use it. For you is a stress make this exe?
