### ISSUE TITLE
Projector Crash

### ISSUE THREAD

**Issue by McyD** [SEServerExtender/SEServerExtender#92]
Using latest version, v1.101.29.576-alpha, noticed that loading a projection has a tendency to crash a server, does not happen every time, but does happen quite often.

**Comment by GornyakManiac** [comment]
Do you use automated cleanups functinon in Essentials plugin?

**Comment by McyD** [comment]
Yes.  However, I should have specified that the projector crash happens when initially loading a projection.  We have no problems once the projection loads, and have multiple projections on at once for days at a time.

**Comment by GornyakManiac** [comment]
Sorry, i don't exactly understand your problem due to bad English knowlege. 
Crashes at cleanup happen because Essentials tries to delete projections like any other grids when they meet the conditions of automated cleanup.

**Comment by McyD** [comment]
Okay, another way to say it.  The crashes do not happen due to cleanup, they only happen when first loading a Projection and has only started since the last release of SESE.  So either a projection loads or the server crashes.

**Comment by McyD** [comment]
Closing this as the problem has not appeared in quite sometime.
