### ISSUE TITLE
SESE-Crash

### ISSUE THREAD

**Issue by chaos234** [SEServerExtender/SEServerExtender#96]
If I want some information from some entities then there will be the following error:

2015-10-22 09:24:26.7135|Info|SEServerExtender.Program.Start|Exception - {0}
    |System.ServiceModel.AddressAlreadyInUseException: HTTP konnte URL "http://+:5353/ServerService/" nicht registrieren. Eine andere Anwendung hat diese URL bereits bei HTTP.SYS registriert. ---> System.Net.HttpListenerException: Fehler beim Abhören von Präfix http://+:5353/ServerService/, da es mit einer vorhandenen Registrierung auf dem Computer in Konflikt steht.
   bei System.Net.HttpListener.AddAllPrefixes()
   bei System.Net.HttpListener.Start()
   bei System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
   bei System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   bei System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   bei System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.HttpChannelListener`1.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Channels.DatagramChannelDemuxer`2.OnOuterListenerOpen(ChannelDemuxerFilter filter, IChannelListener listener, TimeSpan timeout)
   bei System.ServiceModel.Channels.SingletonChannelListener`3.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.NegotiationTokenAuthenticator`1.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.CommunicationObjectSecurityTokenAuthenticator.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.SymmetricSecurityProtocolFactory.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.SecuritySessionSecurityTokenAuthenticator.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.CommunicationObjectSecurityTokenAuthenticator.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.SecuritySessionServerSettings.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Security.SecurityListenerSettingsLifetimeManager.Open(TimeSpan timeout)
   bei System.ServiceModel.Channels.SecurityChannelListener`1.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   bei System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   bei SEServerExtender.Program.Start(String[] args)
Fehler beim Abhören von Präfix http://+:5353/ServerService/, da es mit einer vorhandenen Registrierung auf dem Computer in Konflikt steht. System.Net.HttpListenerException Void AddAllPrefixes()    bei System.Net.HttpListener.AddAllPrefixes()
   bei System.Net.HttpListener.Start()
   bei System.ServiceModel.Channels.SharedHttpTransportManager.OnOpen()
2015-10-22 09:26:25.2419|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments:

Hope, that there will be a solution in the future, because some informations are also missing.

**Comment by Cryptonat** [comment]
Same issue on my end. Error log is identical.
