### ISSUE TITLE
Server doesn't show in server browser

### ISSUE THREAD

**Issue by strikerlord** [SEServerExtender/SEServerExtender#98]
we are having problems with our server showing up in the server browser or connecting to it via a steam link, it simply doesnt work. The game configs do work when we start the game without Server extender. disabeling the firewall has no effect either so that is not the problem (server is running in a DMZ).

we are running the setup on a Server 2012 R2 machine, and if we do the same setup on a W10 machine it does work, unfortunatly, we cannot figure out why it is not working on Server2012 R2.

On the system everything seems to run fine, but from a client it is not possible to find the server as long as we have Server extender enabled.

Please help and let me know what other information is needed.

**Comment by rexxar-tc** [comment]
First off, using a DMZ is a really bad idea, just set your router to forward port 27016 to your server.

It sounds to me like SEServerExtender.exe is being blocked by Windows firewall. You should explicitly add it as an exception.

**Comment by t984447** [comment]
We have a similar issue on a Vanilla SE server on Win SRV 2012 R2, however it dosent even work locally (Through VPN). Does yours?
